spotinst/terraform-spotinst-ocean-aws-k8s

- .gitignore
- README.md
- ocean.tf
- variables.tf
update default variable value required argument
> update default https_token variable

- ocean.tf
- variables.tf
Added field utilize_commitments to module as part of SPOTAUT-12409.
Field was present in spotinst-provider but not exercised in module.
> Added field utilize_commitments to module

- CHANGELOG.md
> Changelog update for v0.2.4

- CHANGELOG.md
> changelog for version v0.2.5

- variables.tf
Reduced grace period to 300.
Ref: https://spotinst.atlassian.net/browse/SPOTAUT-15658
> Reduced grace period

- CHANGELOG.md
> changelog v0.3.0

- CHANGELOG.md
> Changelog 0.4.0

- README.md
- examples/basic/main.tf
- ocean.tf
- variables.tf
Fixed `BDM` required field issue with default value `null`.
Ref: https://spotinst.atlassian.net/browse/SPOTAUT-17348
> Fixed `BDM` required field issue with default value `null`.

- CHANGELOG.md
> changelog 0.5.0

- CHANGELOG.md
> changelog v0.6.0

- .terraform-registry
> change owner request

- README.md
- examples/basic/main.tf
- examples/basic/versions.tf
- ocean.tf
- variables.tf
fixed BDM object to accept multiple blocks as it is array of an object
https://spotinst.atlassian.net/browse/SPOTAUT-17750
> fix for BDM object

- CHANGELOG.md
> changelog v1.1.0

- CHANGELOG.md
> changelog 1.2.0

- CHANGELOG.md
> Changelog 1.3.0

- examples/load_balancer/main.tf
- ocean.tf
- variables.tf
added support for `attach_load_balancer` and `detach_load_balancer` in ocean aws cluster
https://spotinst.atlassian.net/browse/SPOTAUT-18616
> added support for `attach_load_balancer` and `detach_load_balancer` in ocean aws cluster

- CHANGELOG.md
> changelog v1.4.0

- README.md
updated controller v2 reference
https://spotinst.atlassian.net/browse/SPOTAUT-19842
> updated controller v2 reference

- CHANGELOG.md
> Changelog 1.5.0

- CHANGELOG.md
> Changelog v1.9.0

- CHANGELOG.md
> Changelog_v1.9.1
